stages:
  - init

get-version:
  stage: init
  image: alpine:latest
  tags:
    - mnt-pipe
  script:
    - VERSION=$(sed -n 's/version = \"\(.*\)\"/\1/p' package.py)
    - echo "VERSION=${VERSION}" > version_info.txt
  artifacts:
    reports:
      dotenv: version_info.txt
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual
